{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Telegraf",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "display_name",
       "operator": "=",
       "value": "Telegraf Data Collector Service"
      }
     ]
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "query": "SELECT mean(\"startup_mode\") FROM \"win_services\" WHERE (\"display_name\" = 'telegraf') AND $timeFilter GROUP BY time($__interval), \"display_name\" fill(null)",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "grafana",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "query": "SELECT mean(\"startup_mode\") FROM \"win_services\" WHERE (\"display_name\" = 'telegraf') AND $timeFilter GROUP BY time($__interval), \"display_name\" fill(null)",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "Misc" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page faults sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% commited bytes in use" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Processor Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg disk sec read" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg disk sec write" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg disk queue length" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Disk_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  },
  {
   "title": "Net",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $DESKTOP-JHIFNH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes total" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-JHIFNH0" }
     ]
    }
   ]
  }
 ]
}